name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly-2023-02-01
          override: true
          components: rust-src,cargo
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: NotPetyaAgain
        path: target/release/notpetyaagain_boot
